[package]
name = "imgcompress"
version = "0.1.0"
authors = ["Daniel Xu <dxu@dxuuu.xyz>"]
edition = "2018"

[[bin]]
name = "imgcompress"
path = "src/bin/main.rs"

[dependencies]
anyhow = "1.0"
rmp-serde = "0.14"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3"
