[package]
name = "mutator"
version = "0.1.0"
authors = ["Daniel Xu <dxu@dxuuu.xyz>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
fuzzmutator = "0.2"
imgcompress = { path = "../imgcompress" }
libc = "0.2"
rmp-serde = "0.14"
serde = "1.0"
