[package]
name = "runner"
version = "0.1.0"
authors = ["Daniel Xu <dxu@dxuuu.xyz>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
libc = "0.2"
loopdev = "0.2"
nix = "0.18"
structopt = "0.3"
sys-mount = "1.2"
